class Share < ActiveRecord::Base

  mount_uploader :file, FileUploader
  before_save :update_file_attributes

  IMAGE_VERSIONS = ['thumb', 'medium']
  IMAGE_VERSIONS_TO_BE_COUNT = [] # except full version that count by default

  belongs_to :user

  validates :file, :original_filename, presence: true
  validates :user, presence: true

  # Deletes file with share
  before_destroy do
    remove_file!
  end

  #scope :images, where("content_type LIKE 'image%'")

  # Using in specs only
  def filename
    self.file.to_s.split('/').last
  end

  # Restrict filename to 50 symbols
  def short_original_filename(size=50)
    self.original_filename.length > size ? self.original_filename[0...size] + '...' : self.original_filename
  end

  def image?
    #MIME::Types.type_for(self.file.url).first.content_type.start_with? 'image'
    self.content_type.start_with? 'image' and not self.content_type.end_with? 'tiff'   #Tiff files are not processible
  end

  def turn_publicity
    self.public ? false : true
  end

  # Filter by content type
  #def self.type(shares, type)
  #  shares.where("content_type LIKE ?", "%#{type}%")
  #end

  def file_icon_class
    case self.content_type
      when 'application/vnd.hzn-3d-crossword'
        'x3d'
      when 'video/3gpp'
        '3gp'
      when 'video/3gpp2'
        '3g2'
      when 'application/vnd.mseq'
        'mseq'
      when 'application/vnd.3m.post-it-notes'
        'pwn'
      when 'application/vnd.3gpp.pic-bw-large'
        'plb'
      when 'application/vnd.3gpp.pic-bw-small'
        'psb'
      when 'application/vnd.3gpp.pic-bw-var'
        'pvb'
      when 'application/vnd.3gpp2.tcap'
        'tcap'
      when 'application/x-7z-compressed'
        '7z'
      when 'application/x-abiword'
        'abw'
      when 'application/x-ace-compressed'
        'ace'
      when 'application/vnd.americandynamics.acc'
        'acc'
      when 'application/vnd.acucobol'
        'acu'
      when 'application/vnd.acucorp'
        'atc'
      when 'audio/adpcm'
        'adp'
      when 'application/x-authorware-bin'
        'aab'
      when 'application/x-authorware-map'
        'aam'
      when 'application/x-authorware-seg'
        'aas'
      when 'application/vnd.adobe.air-application-installer-package+zip'
        'air'
      when 'application/x-shockwave-flash'
        'swf'
      when 'application/vnd.adobe.fxp'
        'fxp'
      when 'application/pdf'
        'pdf'
      when 'application/vnd.cups-ppd'
        'ppd'
      when 'application/x-director'
        'dir'
      when 'application/vnd.adobe.xdp+xml'
        'xdp'
      when 'application/vnd.adobe.xfdf'
        'xfdf'
      when 'audio/x-aac'
        'aac'
      when 'application/vnd.ahead.space'
        'ahead'
      when 'application/vnd.airzip.filesecure.azf'
        'azf'
      when 'application/vnd.airzip.filesecure.azs'
        'azs'
      when 'application/vnd.amazon.ebook'
        'azw'
      when 'application/vnd.amiga.ami'
        'ami'
      when 'application/andrew-inset'
        'N/A'
      when 'application/vnd.android.package-archive'
        'apk'
      when 'application/vnd.anser-web-certificate-issue-initiation'
        'cii'
      when 'application/vnd.anser-web-funds-transfer-initiation'
        'fti'
      when 'application/vnd.antix.game-component'
        'atx'
      when 'application/vnd.apple.installer+xml'
        'mpkg'
      when 'application/applixware'
        'aw'
      when 'application/vnd.hhe.lesson-player'
        'les'
      when 'application/vnd.aristanetworks.swi'
        'swi'
      when 'text/x-asm'
        's'
      when 'application/atomcat+xml'
        'atomcat'
      when 'application/atomsvc+xml'
        'atomsvc'
      when 'application/atom+xml'
        'atom, xml'
      when 'application/pkix-attr-cert'
        'ac'
      when 'audio/x-aiff'
        'aif'
      when 'video/x-msvideo'
        'avi'
      when 'application/vnd.audiograph'
        'aep'
      when 'image/vnd.dxf'
        'dxf'
      when 'model/vnd.dwf'
        'dwf'
      when 'text/plain-bas'
        'par'
      when 'application/x-bcpio'
        'bcpio'
      when 'application/octet-stream'
        'bin'
      when 'image/bmp'
        'bmp'
      when 'application/x-bittorrent'
        'torrent'
      when 'application/vnd.rim.cod'
        'cod'
      when 'application/vnd.blueice.multipass'
        'mpm'
      when 'application/vnd.bmi'
        'bmi'
      when 'application/x-sh'
        'sh'
      when 'image/prs.btif'
        'btif'
      when 'application/vnd.businessobjects'
        'rep'
      when 'application/x-bzip'
        'bz'
      when 'application/x-bzip2'
        'bz2'
      when 'application/x-csh'
        'csh'
      when 'text/x-c'
        'c'
      when 'application/vnd.chemdraw+xml'
        'cdxml'
      when 'text/css'
        'css'
      when 'chemical/x-cdx'
        'cdx'
      when 'chemical/x-cml'
        'cml'
      when 'chemical/x-csml'
        'csml'
      when 'application/vnd.contact.cmsg'
        'cdbcmsg'
      when 'application/vnd.claymore'
        'cla'
      when 'application/vnd.clonk.c4group'
        'c4g'
      when 'image/vnd.dvb.subtitle'
        'sub'
      when 'application/cdmi-capability'
        'cdmia'
      when 'application/cdmi-container'
        'cdmic'
      when 'application/cdmi-domain'
        'cdmid'
      when 'application/cdmi-object'
        'cdmio'
      when 'application/cdmi-queue'
        'cdmiq'
      when 'application/vnd.cluetrust.cartomobile-config'
        'c11amc'
      when 'application/vnd.cluetrust.cartomobile-config-pkg'
        'c11amz'
      when 'image/x-cmu-raster'
        'ras'
      when 'model/vnd.collada+xml'
        'dae'
      when 'text/csv'
        'csv'
      when 'application/mac-compactpro'
        'cpt'
      when 'application/vnd.wap.wmlc'
        'wmlc'
      when 'image/cgm'
        'cgm'
      when 'x-conference/x-cooltalk'
        'ice'
      when 'image/x-cmx'
        'cmx'
      when 'application/vnd.xara'
        'xar'
      when 'application/vnd.cosmocaller'
        'cmc'
      when 'application/x-cpio'
        'cpio'
      when 'application/vnd.crick.clicker'
        'clkx'
      when 'application/vnd.crick.clicker.keyboard'
        'clkk'
      when 'application/vnd.crick.clicker.palette'
        'clkp'
      when 'application/vnd.crick.clicker.template'
        'clkt'
      when 'application/vnd.crick.clicker.wordbank'
        'clkw'
      when 'application/vnd.criticaltools.wbs+xml'
        'wbs'
      when 'application/vnd.rig.cryptonote'
        'cryptonote'
      when 'chemical/x-cif'
        'cif'
      when 'chemical/x-cmdf'
        'cmdf'
      when 'application/cu-seeme'
        'cu'
      when 'application/prs.cww'
        'cww'
      when 'text/vnd.curl'
        'curl'
      when 'text/vnd.curl.dcurl'
        'dcurl'
      when 'text/vnd.curl.mcurl'
        'mcurl'
      when 'text/vnd.curl.scurl'
        'scurl'
      when 'application/vnd.curl.car'
        'car'
      when 'application/vnd.curl.pcurl'
        'pcurl'
      when 'application/vnd.yellowriver-custom-menu'
        'cmp'
      when 'application/dssc+der'
        'dssc'
      when 'application/dssc+xml'
        'xdssc'
      when 'application/x-debian-package'
        'deb'
      when 'audio/vnd.dece.audio'
        'uva'
      when 'image/vnd.dece.graphic'
        'uvi'
      when 'video/vnd.dece.hd'
        'uvh'
      when 'video/vnd.dece.mobile'
        'uvm'
      when 'video/vnd.uvvu.mp4'
        'uvu'
      when 'video/vnd.dece.pd'
        'uvp'
      when 'video/vnd.dece.sd'
        'uvs'
      when 'video/vnd.dece.video'
        'uvv'
      when 'application/x-dvi'
        'dvi'
      when 'application/vnd.fdsn.seed'
        'seed'
      when 'application/x-dtbook+xml'
        'dtb'
      when 'application/x-dtbresource+xml'
        'res'
      when 'application/vnd.dvb.ait'
        'ait'
      when 'application/vnd.dvb.service'
        'svc'
      when 'audio/vnd.digital-winds'
        'eol'
      when 'image/vnd.djvu'
        'djvu'
      when 'application/xml-dtd'
        'dtd'
      when 'application/vnd.dolby.mlp'
        'mlp'
      when 'application/x-doom'
        'wad'
      when 'application/vnd.dpgraph'
        'dpg'
      when 'audio/vnd.dra'
        'dra'
      when 'application/vnd.dreamfactory'
        'dfac'
      when 'audio/vnd.dts'
        'dts'
      when 'audio/vnd.dts.hd'
        'dtshd'
      when 'image/vnd.dwg'
        'dwg'
      when 'application/vnd.dynageo'
        'geo'
      when 'application/ecmascript'
        'es'
      when 'application/vnd.ecowin.chart'
        'mag'
      when 'image/vnd.fujixerox.edmics-mmr'
        'mmr'
      when 'image/vnd.fujixerox.edmics-rlc'
        'rlc'
      when 'application/exi'
        'exi'
      when 'application/vnd.proteus.magazine'
        'mgz'
      when 'application/epub+zip'
        'epub'
      when 'message/rfc822'
        'eml'
      when 'application/vnd.enliven'
        'nml'
      when 'application/vnd.is-xpr'
        'xpr'
      when 'image/vnd.xiff'
        'xif'
      when 'application/vnd.xfdl'
        'xfdl'
      when 'application/emma+xml'
        'emma'
      when 'application/vnd.ezpix-album'
        'ez2'
      when 'application/vnd.ezpix-package'
        'ez3'
      when 'image/vnd.fst'
        'fst'
      when 'video/vnd.fvt'
        'fvt'
      when 'image/vnd.fastbidsheet'
        'fbs'
      when 'application/vnd.denovo.fcselayout-link'
        'fe_launch'
      when 'video/x-f4v'
        'f4v'
      when 'video/x-flv'
        'flv'
      when 'image/vnd.fpx'
        'fpx'
      when 'image/vnd.net-fpx'
        'npx'
      when 'text/vnd.fmi.flexstor'
        'flx'
      when 'video/x-fli'
        'fli'
      when 'application/vnd.fluxtime.clip'
        'ftc'
      when 'application/vnd.fdf'
        'fdf'
      when 'text/x-fortran'
        'f'
      when 'application/vnd.mif'
        'mif'
      when 'application/vnd.framemaker'
        'fm'
      when 'image/x-freehand'
        'fh'
      when 'application/vnd.fsc.weblaunch'
        'fsc'
      when 'application/vnd.frogans.fnc'
        'fnc'
      when 'application/vnd.frogans.ltf'
        'ltf'
      when 'application/vnd.fujixerox.ddd'
        'ddd'
      when 'application/vnd.fujixerox.docuworks'
        'xdw'
      when 'application/vnd.fujixerox.docuworks.binder'
        'xbd'
      when 'application/vnd.fujitsu.oasys'
        'oas'
      when 'application/vnd.fujitsu.oasys2'
        'oa2'
      when 'application/vnd.fujitsu.oasys3'
        'oa3'
      when 'application/vnd.fujitsu.oasysgp'
        'fg5'
      when 'application/vnd.fujitsu.oasysprs'
        'bh2'
      when 'application/x-futuresplash'
        'spl'
      when 'application/vnd.fuzzysheet'
        'fzs'
      when 'image/g3fax'
        'g3'
      when 'application/vnd.gmx'
        'gmx'
      when 'model/vnd.gtw'
        'gtw'
      when 'application/vnd.genomatix.tuxedo'
        'txd'
      when 'application/vnd.geogebra.file'
        'ggb'
      when 'application/vnd.geogebra.tool'
        'ggt'
      when 'model/vnd.gdl'
        'gdl'
      when 'application/vnd.geometry-explorer'
        'gex'
      when 'application/vnd.geonext'
        'gxt'
      when 'application/vnd.geoplan'
        'g2w'
      when 'application/vnd.geospace'
        'g3w'
      when 'application/x-font-ghostscript'
        'gsf'
      when 'application/x-font-bdf'
        'bdf'
      when 'application/x-gtar'
        'gtar'
      when 'application/x-texinfo'
        'texinfo'
      when 'application/x-gnumeric'
        'gnumeric'
      when 'application/vnd.google-earth.kml+xml'
        'kml'
      when 'application/vnd.google-earth.kmz'
        'kmz'
      when 'application/vnd.grafeq'
        'gqf'
      when 'image/gif'
        'gif'
      when 'text/vnd.graphviz'
        'gv'
      when 'application/vnd.groove-account'
        'gac'
      when 'application/vnd.groove-help'
        'ghf'
      when 'application/vnd.groove-identity-message'
        'gim'
      when 'application/vnd.groove-injector'
        'grv'
      when 'application/vnd.groove-tool-message'
        'gtm'
      when 'application/vnd.groove-tool-template'
        'tpl'
      when 'application/vnd.groove-vcard'
        'vcg'
      when 'video/h261'
        'h261'
      when 'video/h263'
        'h263'
      when 'video/h264'
        'h264'
      when 'application/vnd.hp-hpid'
        'hpid'
      when 'application/vnd.hp-hps'
        'hps'
      when 'application/x-hdf'
        'hdf'
      when 'audio/vnd.rip'
        'rip'
      when 'application/vnd.hbci'
        'hbci'
      when 'application/vnd.hp-jlyt'
        'jlt'
      when 'application/vnd.hp-pcl'
        'pcl'
      when 'application/vnd.hp-hpgl'
        'hpgl'
      when 'application/vnd.yamaha.hv-script'
        'hvs'
      when 'application/vnd.yamaha.hv-dic'
        'hvd'
      when 'application/vnd.yamaha.hv-voice'
        'hvp'
      when 'application/vnd.hydrostatix.sof-data'
        'sfd-hdstx'
      when 'application/hyperstudio'
        'stk'
      when 'application/vnd.hal+xml'
        'hal'
      when 'text/html'
        'html'
      when 'application/vnd.ibm.rights-management'
        'irm'
      when 'application/vnd.ibm.secure-container'
        'sc'
      when 'text/calendar'
        'ics'
      when 'application/vnd.iccprofile'
        'icc'
      when 'image/x-icon'
        'ico'
      when 'application/vnd.igloader'
        'igl'
      when 'image/ief'
        'ief'
      when 'application/vnd.immervision-ivp'
        'ivp'
      when 'application/vnd.immervision-ivu'
        'ivu'
      when 'application/reginfo+xml'
        'rif'
      when 'text/vnd.in3d.3dml'
        '3dml'
      when 'text/vnd.in3d.spot'
        'spot'
      when 'model/iges'
        'igs'
      when 'application/vnd.intergeo'
        'i2g'
      when 'application/vnd.cinderella'
        'cdy'
      when 'application/vnd.intercon.formnet'
        'xpw'
      when 'application/vnd.isac.fcs'
        'fcs'
      when 'application/ipfix'
        'ipfix'
      when 'application/pkix-cert'
        'cer'
      when 'application/pkixcmp'
        'pki'
      when 'application/pkix-crl'
        'crl'
      when 'application/pkix-pkipath'
        'pkipath'
      when 'application/vnd.insors.igm'
        'igm'
      when 'application/vnd.ipunplugged.rcprofile'
        'rcprofile'
      when 'application/vnd.irepository.package+xml'
        'irp'
      when 'text/vnd.sun.j2me.app-descriptor'
        'jad'
      when 'application/java-archive'
        'jar'
      when 'application/java-vm'
        'class'
      when 'application/x-java-jnlp-file'
        'jnlp'
      when 'application/java-serialized-object'
        'ser'
      when 'text/x-java-source,java'
        'java'
      when 'application/javascript'
        'js'
      when 'application/json'
        'json'
      when 'application/vnd.joost.joda-archive'
        'joda'
      when 'video/jpm'
        'jpm'
      when 'image/jpeg'
        'jpeg, jpg'
      when 'video/jpeg'
        'jpgv'
      when 'application/vnd.kahootz'
        'ktz'
      when 'application/vnd.chipnuts.karaoke-mmd'
        'mmd'
      when 'application/vnd.kde.karbon'
        'karbon'
      when 'application/vnd.kde.kchart'
        'chrt'
      when 'application/vnd.kde.kformula'
        'kfo'
      when 'application/vnd.kde.kivio'
        'flw'
      when 'application/vnd.kde.kontour'
        'kon'
      when 'application/vnd.kde.kpresenter'
        'kpr'
      when 'application/vnd.kde.kspread'
        'ksp'
      when 'application/vnd.kde.kword'
        'kwd'
      when 'application/vnd.kenameaapp'
        'htke'
      when 'application/vnd.kidspiration'
        'kia'
      when 'application/vnd.kinar'
        'kne'
      when 'application/vnd.kodak-descriptor'
        'sse'
      when 'application/vnd.las.las+xml'
        'lasxml'
      when 'application/x-latex'
        'latex'
      when 'application/vnd.llamagraphics.life-balance.desktop'
        'lbd'
      when 'application/vnd.llamagraphics.life-balance.exchange+xml'
        'lbe'
      when 'application/vnd.jam'
        'jam'
      when 'application/vnd.lotus-1-2-3'
        '0,123'
      when 'application/vnd.lotus-approach'
        'apr'
      when 'application/vnd.lotus-freelance'
        'pre'
      when 'application/vnd.lotus-notes'
        'nsf'
      when 'application/vnd.lotus-organizer'
        'org'
      when 'application/vnd.lotus-screencam'
        'scm'
      when 'application/vnd.lotus-wordpro'
        'lwp'
      when 'audio/vnd.lucent.voice'
        'lvp'
      when 'audio/x-mpegurl'
        'm3u'
      when 'video/x-m4v'
        'm4v'
      when 'application/mac-binhex40'
        'hqx'
      when 'application/vnd.macports.portpkg'
        'portpkg'
      when 'application/vnd.osgeo.mapguide.package'
        'mgp'
      when 'application/marc'
        'mrc'
      when 'application/marcxml+xml'
        'mrcx'
      when 'application/mxf'
        'mxf'
      when 'application/vnd.wolfram.player'
        'nbp'
      when 'application/mathematica'
        'ma'
      when 'application/mathml+xml'
        'mathml'
      when 'application/mbox'
        'mbox'
      when 'application/vnd.medcalcdata'
        'mc1'
      when 'application/mediaservercontrol+xml'
        'mscml'
      when 'application/vnd.mediastation.cdkey'
        'cdkey'
      when 'application/vnd.mfer'
        'mwf'
      when 'application/vnd.mfmp'
        'mfm'
      when 'model/mesh'
        'msh'
      when 'application/mads+xml'
        'mads'
      when 'application/mets+xml'
        'mets'
      when 'application/mods+xml'
        'mods'
      when 'application/metalink4+xml'
        'meta4'
      when 'application/vnd.ms-powerpoint.template.macroenabled.12'
        'potm'
      when 'application/vnd.ms-word.document.macroenabled.12'
        'docm'
      when 'application/vnd.ms-word.template.macroenabled.12'
        'dotm'
      when 'application/vnd.mcd'
        'mcd'
      when 'application/vnd.micrografx.flo'
        'flo'
      when 'application/vnd.micrografx.igx'
        'igx'
      when 'application/vnd.eszigno3+xml'
        'es3'
      when 'application/x-msaccess'
        'mdb'
      when 'video/x-ms-asf'
        'asf'
      when 'application/x-msdownload'
        'exe'
      when 'application/vnd.ms-artgalry'
        'cil'
      when 'application/vnd.ms-cab-compressed'
        'cab'
      when 'application/vnd.ms-ims'
        'ims'
      when 'application/x-ms-application'
        'application'
      when 'application/x-msclip'
        'clp'
      when 'image/vnd.ms-modi'
        'mdi'
      when 'application/vnd.ms-fontobject'
        'eot'
      when 'application/vnd.ms-excel'
        'xls'
      when 'application/vnd.ms-excel.addin.macroenabled.12'
        'xlam'
      when 'application/vnd.ms-excel.sheet.binary.macroenabled.12'
        'xlsb'
      when 'application/vnd.ms-excel.template.macroenabled.12'
        'xltm'
      when 'application/vnd.ms-excel.sheet.macroenabled.12'
        'xlsm'
      when 'application/vnd.ms-htmlhelp'
        'chm'
      when 'application/x-mscardfile'
        'crd'
      when 'application/vnd.ms-lrm'
        'lrm'
      when 'application/x-msmediaview'
        'mvb'
      when 'application/x-msmoney'
        'mny'
      when 'application/vnd.openxmlformats-officedocument.presentationml.presentation'
        'pptx'
      when 'application/vnd.openxmlformats-officedocument.presentationml.slide'
        'sldx'
      when 'application/vnd.openxmlformats-officedocument.presentationml.slideshow'
        'ppsx'
      when 'application/vnd.openxmlformats-officedocument.presentationml.template'
        'potx'
      when 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        'xlsx'
      when 'application/vnd.openxmlformats-officedocument.spreadsheetml.template'
        'xltx'
      when 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        'docx'
      when 'application/vnd.openxmlformats-officedocument.wordprocessingml.template'
        'dotx'
      when 'application/x-msbinder'
        'obd'
      when 'application/vnd.ms-officetheme'
        'thmx'
      when 'application/onenote'
        'onetoc'
      when 'audio/vnd.ms-playready.media.pya'
        'pya'
      when 'video/vnd.ms-playready.media.pyv'
        'pyv'
      when 'application/vnd.ms-powerpoint'
        'ppt'
      when 'application/vnd.ms-powerpoint.addin.macroenabled.12'
        'ppam'
      when 'application/vnd.ms-powerpoint.slide.macroenabled.12'
        'sldm'
      when 'application/vnd.ms-powerpoint.presentation.macroenabled.12'
        'pptm'
      when 'application/vnd.ms-powerpoint.slideshow.macroenabled.12'
        'ppsm'
      when 'application/vnd.ms-project'
        'mpp'
      when 'application/x-mspublisher'
        'pub'
      when 'application/x-msschedule'
        'scd'
      when 'application/x-silverlight-app'
        'xap'
      when 'application/vnd.ms-pki.stl'
        'stl'
      when 'application/vnd.ms-pki.seccat'
        'cat'
      when 'application/vnd.visio'
        'vsd'
      when 'video/x-ms-wm'
        'wm'
      when 'audio/x-ms-wma'
        'wma'
      when 'audio/x-ms-wax'
        'wax'
      when 'video/x-ms-wmx'
        'wmx'
      when 'application/x-ms-wmd'
        'wmd'
      when 'application/vnd.ms-wpl'
        'wpl'
      when 'application/x-ms-wmz'
        'wmz'
      when 'video/x-ms-wmv'
        'wmv'
      when 'video/x-ms-wvx'
        'wvx'
      when 'application/x-msmetafile'
        'wmf'
      when 'application/x-msterminal'
        'trm'
      when 'application/msword'
        'doc'
      when 'application/x-mswrite'
        'wri'
      when 'application/vnd.ms-works'
        'wps'
      when 'application/x-ms-xbap'
        'xbap'
      when 'application/vnd.ms-xpsdocument'
        'xps'
      when 'audio/midi'
        'mid'
      when 'application/vnd.ibm.minipay'
        'mpy'
      when 'application/vnd.ibm.modcap'
        'afp'
      when 'application/vnd.jcp.javame.midlet-rms'
        'rms'
      when 'application/vnd.tmobile-livetv'
        'tmo'
      when 'application/x-mobipocket-ebook'
        'prc'
      when 'application/vnd.mobius.mbk'
        'mbk'
      when 'application/vnd.mobius.dis'
        'dis'
      when 'application/vnd.mobius.plc'
        'plc'
      when 'application/vnd.mobius.mqy'
        'mqy'
      when 'application/vnd.mobius.msl'
        'msl'
      when 'application/vnd.mobius.txf'
        'txf'
      when 'application/vnd.mobius.daf'
        'daf'
      when 'text/vnd.fly'
        'fly'
      when 'application/vnd.mophun.certificate'
        'mpc'
      when 'application/vnd.mophun.application'
        'mpn'
      when 'video/mj2'
        'mj2'
      when 'audio/mpeg'
        'mpga'
      when 'video/vnd.mpegurl'
        'mxu'
      when 'video/mpeg'
        'mpeg'
      when 'application/mp21'
        'm21'
      when 'audio/mp4'
        'mp4a'
      when 'video/mp4'
        'mp4'
      when 'application/mp4'
        'mp4'
      when 'application/vnd.apple.mpegurl'
        'm3u8'
      when 'application/vnd.musician'
        'mus'
      when 'application/vnd.muvee.style'
        'msty'
      when 'application/xv+xml'
        'mxml'
      when 'application/vnd.nokia.n-gage.data'
        'ngdat'
      when 'application/vnd.nokia.n-gage.symbian.install'
        'n-gage'
      when 'application/x-dtbncx+xml'
        'ncx'
      when 'application/x-netcdf'
        'nc'
      when 'application/vnd.neurolanguage.nlu'
        'nlu'
      when 'application/vnd.dna'
        'dna'
      when 'application/vnd.noblenet-directory'
        'nnd'
      when 'application/vnd.noblenet-sealer'
        'nns'
      when 'application/vnd.noblenet-web'
        'nnw'
      when 'application/vnd.nokia.radio-preset'
        'rpst'
      when 'application/vnd.nokia.radio-presets'
        'rpss'
      when 'text/n3'
        'n3'
      when 'application/vnd.novadigm.edm'
        'edm'
      when 'application/vnd.novadigm.edx'
        'edx'
      when 'application/vnd.novadigm.ext'
        'ext'
      when 'application/vnd.flographit'
        'gph'
      when 'audio/vnd.nuera.ecelp4800'
        'ecelp4800'
      when 'audio/vnd.nuera.ecelp7470'
        'ecelp7470'
      when 'audio/vnd.nuera.ecelp9600'
        'ecelp9600'
      when 'application/oda'
        'oda'
      when 'application/ogg'
        'ogx'
      when 'audio/ogg'
        'oga'
      when 'video/ogg'
        'ogv'
      when 'application/vnd.oma.dd2+xml'
        'dd2'
      when 'application/vnd.oasis.opendocument.text-web'
        'oth'
      when 'application/oebps-package+xml'
        'opf'
      when 'application/vnd.intu.qbo'
        'qbo'
      when 'application/vnd.openofficeorg.extension'
        'oxt'
      when 'application/vnd.yamaha.openscoreformat'
        'osf'
      when 'audio/webm'
        'weba'
      when 'video/webm'
        'webm'
      when 'application/vnd.oasis.opendocument.chart'
        'odc'
      when 'application/vnd.oasis.opendocument.chart-template'
        'otc'
      when 'application/vnd.oasis.opendocument.database'
        'odb'
      when 'application/vnd.oasis.opendocument.formula'
        'odf'
      when 'application/vnd.oasis.opendocument.formula-template'
        'odft'
      when 'application/vnd.oasis.opendocument.graphics'
        'odg'
      when 'application/vnd.oasis.opendocument.graphics-template'
        'otg'
      when 'application/vnd.oasis.opendocument.image'
        'odi'
      when 'application/vnd.oasis.opendocument.image-template'
        'oti'
      when 'application/vnd.oasis.opendocument.presentation'
        'odp'
      when 'application/vnd.oasis.opendocument.presentation-template'
        'otp'
      when 'application/vnd.oasis.opendocument.spreadsheet'
        'ods'
      when 'application/vnd.oasis.opendocument.spreadsheet-template'
        'ots'
      when 'application/vnd.oasis.opendocument.text'
        'odt'
      when 'application/vnd.oasis.opendocument.text-master'
        'odm'
      when 'application/vnd.oasis.opendocument.text-template'
        'ott'
      when 'image/ktx'
        'ktx'
      when 'application/vnd.sun.xml.calc'
        'sxc'
      when 'application/vnd.sun.xml.calc.template'
        'stc'
      when 'application/vnd.sun.xml.draw'
        'sxd'
      when 'application/vnd.sun.xml.draw.template'
        'std'
      when 'application/vnd.sun.xml.impress'
        'sxi'
      when 'application/vnd.sun.xml.impress.template'
        'sti'
      when 'application/vnd.sun.xml.math'
        'sxm'
      when 'application/vnd.sun.xml.writer'
        'sxw'
      when 'application/vnd.sun.xml.writer.global'
        'sxg'
      when 'application/vnd.sun.xml.writer.template'
        'stw'
      when 'application/x-font-otf'
        'otf'
      when 'application/vnd.yamaha.openscoreformat.osfpvg+xml'
        'osfpvg'
      when 'application/vnd.osgi.dp'
        'dp'
      when 'application/vnd.palm'
        'pdb'
      when 'text/x-pascal'
        'p'
      when 'application/vnd.pawaafile'
        'paw'
      when 'application/vnd.hp-pclxl'
        'pclxl'
      when 'application/vnd.picsel'
        'efif'
      when 'image/x-pcx'
        'pcx'
      when 'image/vnd.adobe.photoshop'
        'psd'
      when 'application/x-photoshop'
        'psd'
      when 'application/pics-rules'
        'prf'
      when 'image/x-pict'
        'pic'
      when 'application/x-chat'
        'chat'
      when 'application/pkcs10'
        'p10'
      when 'application/x-pkcs12'
        'p12'
      when 'application/pkcs7-mime'
        'p7m'
      when 'application/pkcs7-signature'
        'p7s'
      when 'application/x-pkcs7-certreqresp'
        'p7r'
      when 'application/x-pkcs7-certificates'
        'p7b'
      when 'application/pkcs8'
        'p8'
      when 'application/vnd.pocketlearn'
        'plf'
      when 'image/x-portable-anymap'
        'pnm'
      when 'image/x-portable-bitmap'
        'pbm'
      when 'application/x-font-pcf'
        'pcf'
      when 'application/font-tdpfr'
        'pfr'
      when 'application/x-chess-pgn'
        'pgn'
      when 'image/x-portable-graymap'
        'pgm'
      when 'image/png'
        'png'
      when 'image/x-portable-pixmap'
        'ppm'
      when 'application/pskc+xml'
        'pskcxml'
      when 'application/vnd.ctc-posml'
        'pml'
      when 'application/postscript'
        'ai'
      when 'application/x-font-type1'
        'pfa'
      when 'application/vnd.powerbuilder6'
        'pbd'
      when 'application/pgp-encrypted'
        ''
      when 'application/pgp-signature'
        'pgp'
      when 'application/vnd.previewsystems.box'
        'box'
      when 'application/vnd.pvi.ptid1'
        'ptid'
      when 'application/pls+xml'
        'pls'
      when 'application/vnd.pg.format'
        'str'
      when 'application/vnd.pg.osasli'
        'ei6'
      when 'text/prs.lines.tag'
        'dsc'
      when 'application/x-font-linux-psf'
        'psf'
      when 'application/vnd.publishare-delta-tree'
        'qps'
      when 'application/vnd.pmi.widget'
        'wg'
      when 'application/vnd.quark.quarkxpress'
        'qxd'
      when 'application/vnd.epson.esf'
        'esf'
      when 'application/vnd.epson.msf'
        'msf'
      when 'application/vnd.epson.ssf'
        'ssf'
      when 'application/vnd.epson.quickanime'
        'qam'
      when 'application/vnd.intu.qfx'
        'qfx'
      when 'video/quicktime'
        'qt'
      when 'application/x-rar-compressed'
        'rar'
      when 'audio/x-pn-realaudio'
        'ram'
      when 'audio/x-pn-realaudio-plugin'
        'rmp'
      when 'application/rsd+xml'
        'rsd'
      when 'application/vnd.rn-realmedia'
        'rm'
      when 'application/vnd.realvnc.bed'
        'bed'
      when 'application/vnd.recordare.musicxml'
        'mxl'
      when 'application/vnd.recordare.musicxml+xml'
        'musicxml'
      when 'application/relax-ng-compact-syntax'
        'rnc'
      when 'application/vnd.data-vision.rdz'
        'rdz'
      when 'application/rdf+xml'
        'rdf'
      when 'application/vnd.cloanto.rp9'
        'rp9'
      when 'application/vnd.jisp'
        'jisp'
      when 'application/rtf'
        'rtf'
      when 'text/richtext'
        'rtx'
      when 'application/vnd.route66.link66+xml'
        'link66'
      when 'application/rss+xml'
        'rss, xml'
      when 'application/shf+xml'
        'shf'
      when 'application/vnd.sailingtracker.track'
        'st'
      when 'image/svg+xml'
        'svg'
      when 'application/vnd.sus-calendar'
        'sus'
      when 'application/sru+xml'
        'sru'
      when 'application/set-payment-initiation'
        'setpay'
      when 'application/set-registration-initiation'
        'setreg'
      when 'application/vnd.sema'
        'sema'
      when 'application/vnd.semd'
        'semd'
      when 'application/vnd.semf'
        'semf'
      when 'application/vnd.seemail'
        'see'
      when 'application/x-font-snf'
        'snf'
      when 'application/scvp-vp-request'
        'spq'
      when 'application/scvp-vp-response'
        'spp'
      when 'application/scvp-cv-request'
        'scq'
      when 'application/scvp-cv-response'
        'scs'
      when 'application/sdp'
        'sdp'
      when 'text/x-setext'
        'etx'
      when 'video/x-sgi-movie'
        'movie'
      when 'application/vnd.shana.informed.formdata'
        'ifm'
      when 'application/vnd.shana.informed.formtemplate'
        'itp'
      when 'application/vnd.shana.informed.interchange'
        'iif'
      when 'application/vnd.shana.informed.package'
        'ipk'
      when 'application/thraud+xml'
        'tfi'
      when 'application/x-shar'
        'shar'
      when 'image/x-rgb'
        'rgb'
      when 'application/vnd.epson.salt'
        'slt'
      when 'application/vnd.accpac.simply.aso'
        'aso'
      when 'application/vnd.accpac.simply.imp'
        'imp'
      when 'application/vnd.simtech-mindmapper'
        'twd'
      when 'application/vnd.commonspace'
        'csp'
      when 'application/vnd.yamaha.smaf-audio'
        'saf'
      when 'application/vnd.smaf'
        'mmf'
      when 'application/vnd.yamaha.smaf-phrase'
        'spf'
      when 'application/vnd.smart.teacher'
        'teacher'
      when 'application/vnd.svd'
        'svd'
      when 'application/sparql-query'
        'rq'
      when 'application/sparql-results+xml'
        'srx'
      when 'application/srgs'
        'gram'
      when 'application/srgs+xml'
        'grxml'
      when 'application/ssml+xml'
        'ssml'
      when 'application/vnd.koan'
        'skp'
      when 'text/sgml'
        'sgml'
      when 'application/vnd.stardivision.calc'
        'sdc'
      when 'application/vnd.stardivision.draw'
        'sda'
      when 'application/vnd.stardivision.impress'
        'sdd'
      when 'application/vnd.stardivision.math'
        'smf'
      when 'application/vnd.stardivision.writer'
        'sdw'
      when 'application/vnd.stardivision.writer-global'
        'sgl'
      when 'application/vnd.stepmania.stepchart'
        'sm'
      when 'application/x-stuffit'
        'sit'
      when 'application/x-stuffitx'
        'sitx'
      when 'application/vnd.solent.sdkm+xml'
        'sdkm'
      when 'application/vnd.olpc-sugar'
        'xo'
      when 'audio/basic'
        'au'
      when 'application/vnd.wqd'
        'wqd'
      when 'application/vnd.symbian.install'
        'sis'
      when 'application/smil+xml'
        'smi'
      when 'application/vnd.syncml+xml'
        'xsm'
      when 'application/vnd.syncml.dm+wbxml'
        'bdm'
      when 'application/vnd.syncml.dm+xml'
        'xdm'
      when 'application/x-sv4cpio'
        'sv4cpio'
      when 'application/x-sv4crc'
        'sv4crc'
      when 'application/sbml+xml'
        'sbml'
      when 'text/tab-separated-values'
        'tsv'
      when 'image/tiff'
        'tiff'
      when 'application/vnd.tao.intent-module-archive'
        'tao'
      when 'application/x-tar'
        'tar'
      when 'application/x-tcl'
        'tcl'
      when 'application/x-tex'
        'tex'
      when 'application/x-tex-tfm'
        'tfm'
      when 'application/tei+xml'
        'tei'
      when 'text/plain'
        'txt'
      when 'application/vnd.spotfire.dxp'
        'dxp'
      when 'application/vnd.spotfire.sfs'
        'sfs'
      when 'application/timestamped-data'
        'tsd'
      when 'application/vnd.trid.tpt'
        'tpt'
      when 'application/vnd.triscape.mxs'
        'mxs'
      when 'text/troff'
        't'
      when 'application/vnd.trueapp'
        'tra'
      when 'application/x-font-ttf'
        'ttf'
      when 'text/turtle'
        'ttl'
      when 'application/vnd.umajin'
        'umj'
      when 'application/vnd.uoml+xml'
        'uoml'
      when 'application/vnd.unity'
        'unityweb'
      when 'application/vnd.ufdl'
        'ufd'
      when 'text/uri-list'
        'uri'
      when 'application/vnd.uiq.theme'
        'utz'
      when 'application/x-ustar'
        'ustar'
      when 'text/x-uuencode'
        'uu'
      when 'text/x-vcalendar'
        'vcs'
      when 'text/x-vcard'
        'vcf'
      when 'application/x-cdlink'
        'vcd'
      when 'application/vnd.vsf'
        'vsf'
      when 'model/vrml'
        'wrl'
      when 'application/vnd.vcx'
        'vcx'
      when 'model/vnd.mts'
        'mts'
      when 'model/vnd.vtu'
        'vtu'
      when 'application/vnd.visionary'
        'vis'
      when 'video/vnd.vivo'
        'viv'
      when 'application/ccxml+xml,'
        'ccxml'
      when 'application/voicexml+xml'
        'vxml'
      when 'application/x-wais-source'
        'src'
      when 'application/vnd.wap.wbxml'
        'wbxml'
      when 'image/vnd.wap.wbmp'
        'wbmp'
      when 'audio/x-wav'
        'wav'
      when 'application/davmount+xml'
        'davmount'
      when 'application/x-font-woff'
        'woff'
      when 'application/wspolicy+xml'
        'wspolicy'
      when 'image/webp'
        'webp'
      when 'application/vnd.webturbo'
        'wtb'
      when 'application/widget'
        'wgt'
      when 'application/winhlp'
        'hlp'
      when 'text/vnd.wap.wml'
        'wml'
      when 'text/vnd.wap.wmlscript'
        'wmls'
      when 'application/vnd.wap.wmlscriptc'
        'wmlsc'
      when 'application/vnd.wordperfect'
        'wpd'
      when 'application/vnd.wt.stf'
        'stf'
      when 'application/wsdl+xml'
        'wsdl'
      when 'image/x-xbitmap'
        'xbm'
      when 'image/x-xpixmap'
        'xpm'
      when 'image/x-xwindowdump'
        'xwd'
      when 'application/x-x509-ca-cert'
        'der'
      when 'application/x-xfig'
        'fig'
      when 'application/xhtml+xml'
        'xhtml'
      when 'application/xml'
        'xml'
      when 'application/xcap-diff+xml'
        'xdf'
      when 'application/xenc+xml'
        'xenc'
      when 'application/patch-ops-error+xml'
        'xer'
      when 'application/resource-lists+xml'
        'rl'
      when 'application/rls-services+xml'
        'rs'
      when 'application/resource-lists-diff+xml'
        'rld'
      when 'application/xslt+xml'
        'xslt'
      when 'application/xop+xml'
        'xop'
      when 'application/x-xpinstall'
        'xpi'
      when 'application/xspf+xml'
        'xspf'
      when 'application/vnd.mozilla.xul+xml'
        'xul'
      when 'chemical/x-xyz'
        'xyz'
      when 'application/yang'
        'yang'
      when 'application/yin+xml'
        'yin'
      when 'application/vnd.zul'
        'zir'
      when 'application/zip'
        'zip'
      when 'application/vnd.handheld-entertainment+xml'
        'zmm'
      when 'application/vnd.zzazz.deck+xml'
        'zaz'
      when 'application/x-rar'
        'rar'
      when 'audio/aac'
        'aac'
      else
        'file-blank'
    end
  end

  private

  def update_file_attributes
    if file.present? && file_changed?
      self.content_type = file.file.content_type
      self.file_size = file.file.size
    end
  end

end
